linters:
  enable:
    - gosec
    - godot
    - misspell
    - stylecheck

linters-setting:
  stylecheck:
    - go: "1.22.4"
    - checks: ["all", "ST1*"]

issues:
   exclude-use-default: false

output:
  formats:
    - format: colored-line-number

  print-issued-lines: false

  print-linter-name: true