linters:
  enable:
    - gosec
    - godot
    - misspell
    - stylecheck

linters-setting:
  stylecheck:
    - go: "1.22.4"
    - checks: ["all", "ST1*"]
  gosec:
    excludes:
      - G114

issues:
  exclude-use-default: false
  exclude:
    - "ST1000: at least one file in a package should have a package comment"

output:
  format: colored-line-number

  print-issued-lines: false

  print-linter-name: true