version: "3.9"
services:
  api-min: 
    profiles: ['prod'] 
    image: ghcr.io/domicmeia/gcp_practice:min
    ports: 
      - 8080:8080
    build: .
  api-dev: 
    profiles: ['dev'] 
    image: ghcr.io/domicmeia/gcp_practice:dev
    ports: 
      - 8080:8080
    build:
      context: .
      target: dev 
  database:
    image: redis:latest
    ports:
      - 6379:6379 
    volumes:
      - "./data/:/data/"